### ISSUE TITLE
优化建议，在action中手动触发邀请代替提交更改时的触发

### ISSUE THREAD

**Issue by ghostWindows-files** [LinYuanovo/pikpak_auto_invite#24]
由于第一次激活自动邀请需要提交文件更改或者需要手动触发刷邀请时都需要提交文件更改。非常不方便，建议在on与触发器并行的那一行添加workflow_dispatch（允许您在 GitHub 仓库的 Actions 选项卡中手动触发工作流程。）

就这些，下面是AI给出的教程

要设置工作流程以便它可以手动触发或在每天晚上 12 点自动触发，您可以在 `.yml` 配置文件中同时使用 `workflow_dispatch` 和 `schedule` 事件。以下是一个配置示例：

```yaml
name: Manual or Scheduled Python script

on:
  workflow_dispatch:
  schedule:
    # 每天的 UTC 16:00，即东八区时间的 00:00
    - cron: '0 16 * * *'

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Run the script
      run: python run.py
```

在这个配置中：
- `workflow_dispatch` 允许您在 GitHub 仓库的 Actions 选项卡中手动触发工作流程。
- `schedule` 部分设置了一个 cron 表达式，它定义了工作流程应该在 UTC 时间的 16:00 自动触发，这对应于东八区时间的 00:00。

您可以将此配置文件保存到 `.github/workflows` 目录下的 `.yml` 文件中，并根据需要进行调整。这样，您就可以选择手动启动工作流程，或者让它按照计划在每天晚上 12 点自动执行。🌟
